# Import packages

In [87]:
import warnings
warnings.filterwarnings("ignore")

In [88]:
import pandas as pd
import numpy as np
from pypfopt.efficient_frontier import EfficientFrontier
from pypfopt import risk_models
from pypfopt.risk_models import CovarianceShrinkage
from pypfopt import expected_returns
from datetime import datetime
from pandas.tseries.offsets import BDay

In [89]:
import time
import pickle

In [90]:
fund_df = pd.read_csv('data_processor_update/sp500_fundamental_199601_202502.csv')

In [91]:
fund_df.drop_duplicates('gvkey', inplace=True)
fund_df = fund_df[['gvkey','tic']]

# 1. Read Input Data

In [92]:
df_price = pd.read_csv("data_processor_update/sp500_price_199601_202502.csv")

In [93]:
df_price.shape

(4514910, 22)

In [94]:
df_price.columns

Index(['tic', 'cusip', 'permno', 'permco', 'issuno', 'hexcd', 'hsiccd', 'date',
       'bidlo', 'askhi', 'prc', 'adj_close_q', 'vol', 'ret', 'bid', 'ask',
       'shrout', 'cfacpr', 'cfacshr', 'openprc', 'numtrd', 'retx'],
      dtype='object')

In [95]:
# df_price['adj_price'] = df_price['prccd'] / df_price['ajexdi']
df_price['adj_price'] = df_price['adj_close_q']
df_price = pd.merge(df_price, fund_df, on='tic')
# df_price['gvkey'] = df_price['tic']
df_price['datadate'] = df_price['date']

In [96]:
df_price['datadate'] = df_price['datadate'].str[:10]

In [97]:
df_price = df_price[["gvkey", "datadate", 'adj_price']]

In [98]:
len(df_price.gvkey.unique())

741

In [99]:
selected_stock = pd.read_csv("stock_selected.csv",index_col=0)

In [100]:
selected_stock['trade_date'].unique().max(), selected_stock['trade_date'].unique().min()

('2024-12-02', '2001-03-01')

In [101]:
selected_stock=selected_stock[selected_stock.trade_date>='2001-03-01'].reset_index(drop=True)

In [102]:
selected_stock.shape

(17551, 3)

In [103]:
selected_stock.head()

   gvkey  predicted_return  trade_date
0   1661          0.019528  2001-03-01
1   2991          0.018405  2001-03-01
2   5581          0.019699  2001-03-01
3   7620          0.020153  2001-03-01
4  11506          0.018597  2001-03-01

# 2. Get trade date

In [104]:
print("Number of unique stocks selected: ", len(selected_stock.gvkey.unique()))

Number of unique stocks selected:  677

In [105]:
all_date=df_price.datadate.unique()

In [106]:
len(all_date)

7325

In [107]:
trade_date=selected_stock.trade_date.unique()

In [108]:
trade_date

array(['2001-03-01', '2001-06-01', '2001-09-04', '2001-12-03',
       '2002-03-01', '2002-06-03', '2002-09-03', '2002-12-02',
       '2003-03-03', '2003-06-02', '2003-09-02', '2003-12-01',
       '2004-03-01', '2004-06-01', '2004-09-01', '2004-12-01',
       '2005-03-01', '2005-06-01', '2005-09-01', '2005-12-01',
       '2006-03-01', '2006-06-01', '2006-09-01', '2006-12-01',
       '2007-03-01', '2007-06-01', '2007-09-04', '2007-12-03',
       '2008-03-03', '2008-06-02', '2008-09-02', '2008-12-01',
       '2009-03-02', '2009-06-01', '2009-09-01', '2009-12-01',
       '2010-03-01', '2010-06-01', '2010-09-01', '2010-12-01',
       '2011-03-01', '2011-06-01', '2011-09-01', '2011-12-01',
       '2012-03-01', '2012-06-01', '2012-09-04', '2012-12-03',
       '2013-03-01', '2013-06-03', '2013-09-03', '2013-12-02',
       '2014-03-03', '2014-06-02', '2014-09-02', '2014-12-01',
       '2015-03-02', '2015-06-01', '2015-09-01', '2015-12-01',
       '2016-03-01', '2016-06-01', '2016-09-01', '2016-12-01',
       '2017-03-01', '2017-06-01', '2017-09-01', '2017-12-01',
       '2018-03-01', '2018-06-01', '2018-09-04', '2018-12-03',
       '2019-03-01', '2019-06-03', '2019-09-03', '2019-12-02',
       '2020-03-02', '2020-06-01', '2020-09-01', '2020-12-01',
       '2021-03-01', '2021-06-01', '2021-09-01', '2021-12-01',
       '2022-03-01', '2022-06-01', '2022-09-01', '2022-12-01',
       '2023-03-01', '2023-06-01', '2023-09-01', '2023-12-01',
       '2024-03-01', '2024-06-03', '2024-09-03', '2024-12-02'],
      dtype=object)

In [109]:
print("Number of trade dates", len(trade_date))

Number of trade dates 96

# 3. Get daily 1 year return table in each 89 trade period

In [111]:
selected_stock.head()

   gvkey  predicted_return  trade_date
0   1661          0.019528  2001-03-01
1   2991          0.018405  2001-03-01
2   5581          0.019699  2001-03-01
3   7620          0.020153  2001-03-01
4  11506          0.018597  2001-03-01

In [112]:
# took about 9 minutes to run
start = time.time()
all_return_table={}
#all_predicted_return={}
all_stocks_info = {}
#for i in range(0,1):
for i in range(len(trade_date)):
    #match trading date
    index = selected_stock.trade_date==trade_date[i]
    #get the corresponding trade period's selected stocks' name
    stocks_name=selected_stock.gvkey[selected_stock.trade_date==trade_date[i]].values
    temp_info = selected_stock[selected_stock.trade_date==trade_date[i]]
    temp_info = temp_info.reset_index()
    del temp_info['index']
    all_stocks_info[trade_date[i]] = temp_info
    #get the corresponding trade period's selected stocks' predicted return
    asset_expected_return=selected_stock[index].predicted_return.values
    
    
    #determine the business date
    #print(convert_to_yyyymmdd)
    tradedate = pd.to_datetime(trade_date[i])
    ts = datetime(tradedate.year-1, tradedate.month, tradedate.day)
    bd = pd.tseries.offsets.BusinessDay(n =1) 
    new_timestamp = ts - bd 
    all_date = pd.to_datetime(all_date, format="%Y-%m-%d")
    get_date_index=(all_date<tradedate) & (all_date>new_timestamp)
    get_date=all_date[get_date_index]
    #get adjusted price table
    return_table=pd.DataFrame()
    for m in range(len(stocks_name)):
        #get stocks's name
        index_tic=(df_price.gvkey==stocks_name[m])
        #get this stock's all historicall price from sp500_price
        sp500_temp=df_price[index_tic]
        merge_left_data_table = pd.DataFrame(get_date)
        merge_left_data_table.columns = ['datadate']
        #print(merge_left_data_table)
        sp500_temp.datadate = pd.to_datetime(sp500_temp.datadate, format="%Y-%m-%d")
        temp_price=merge_left_data_table.merge(sp500_temp, on=['datadate'], how='left')
        
        temp_price = temp_price.dropna()
        temp_price['daily_return']=temp_price.adj_price.pct_change()
        # return_table=return_table.append(temp_price,ignore_index=True)
        return_table = pd.concat([return_table,temp_price])
    all_return_table[trade_date[i]] = return_table
end = time.time()
print("Time consuming: ", (end-start)/60, " minutes")

Time consuming:  1.772895085811615  minutes

In [113]:
all_return_table

{'2001-03-01':       datadate     gvkey   adj_price  daily_return
 0   2000-03-01    1661.0  806.375793           NaN
 1   2000-03-02    1661.0  837.082153      0.038079
 2   2000-03-03    1661.0  799.700623     -0.044657
 3   2000-03-06    1661.0  819.726257      0.025041
 4   2000-03-07    1661.0  854.437744      0.042345
 ..         ...       ...         ...           ...
 247 2001-02-22  125595.0   17.000000     -0.052265
 248 2001-02-23  125595.0   19.187500      0.128676
 249 2001-02-26  125595.0   20.062500      0.045603
 250 2001-02-27  125595.0   17.812500     -0.112150
 251 2001-02-28  125595.0   16.937500     -0.049123

 [26724 rows x 4 columns],
 '2001-06-01':       datadate     gvkey  adj_price  daily_return
 0   2000-06-01    1380.0  15.726690           NaN
 1   2000-06-02    1380.0  14.896629     -0.052780
 2   2000-06-05    1380.0  15.000383      0.006965
 3   2000-06-06    1380.0  15.593284      0.039526
 4   2000-06-07    1380.0  15.252367     -0.021863
 ..         ...       ...        ...           ...
 247 2001-05-24  138743.0  37.461662      0.076923
 248 2001-05-25  138743.0  36.488640     -0.025974
 249 2001-05-29  138743.0  35.515602     -0.026667
 250 2001-05-30  138743.0  31.623470     -0.109589
 251 2001-05-31  138743.0  31.623470      0.000000

 [35607 rows x 4 columns],
 '2001-09-04':       datadate     gvkey  adj_price  daily_return
 0   2000-09-05    1380.0  16.623709           NaN
 1   2000-09-06    1380.0  16.846550      0.013405
 2   2000-09-07    1380.0  16.965395      0.007055
 3   2000-09-08    1380.0  16.638575     -0.019264
 4   2000-09-11    1380.0  16.712845      0.004464
 ..         ...       ...        ...           ...
 246 2001-08-27  138743.0  21.649923     -0.053191
 247 2001-08-28  138743.0  20.920147     -0.033708
 248 2001-08-29  138743.0  18.974083     -0.093023
 249 2001-08-30  138743.0  17.757801     -0.064102
 250 2001-08-31  138743.0  17.757801      0.000000

 [36554 rows x 4 columns],
 '2001-12-03':       datadate     gvkey  adj_price  daily_return
 0   2000-12-04    1380.0  14.828528           NaN
 1   2000-12-05    1380.0  14.352110     -0.032129
 2   2000-12-06    1380.0  14.352110      0.000000
 3   2000-12-07    1380.0  14.143685     -0.014522
 4   2000-12-08    1380.0  14.292555      0.010526
 ..         ...       ...        ...           ...
 242 2001-11-26  112111.0   1.864000      0.022490
 243 2001-11-27  112111.0   1.815000     -0.026288
 244 2001-11-28  112111.0   1.810000     -0.002755
 245 2001-11-29  112111.0   1.949000      0.076796
 246 2001-11-30  112111.0   1.937000     -0.006157

 [34829 rows x 4 columns],
 '2002-03-01':       datadate     gvkey  adj_price  daily_return
 0   2001-03-01    1380.0  17.291304           NaN
 1   2001-03-02    1380.0  17.673374      0.022096
 2   2001-03-05    1380.0  18.026802      0.019998
 3   2001-03-06    1380.0  18.306181      0.015498
 4   2001-03-07    1380.0  18.540205      0.012784
 ..         ...       ...        ...           ...
 243 2002-02-22  113490.0   3.629665     -0.021052
 244 2002-02-25  113490.0   3.811799      0.050179
 245 2002-02-26  113490.0   3.889858      0.020478
 246 2002-02-27  113490.0   4.098010      0.053511
 247 2002-02-28  113490.0   4.039466     -0.014286

 [31577 rows x 4 columns],
 '2002-06-03':       datadate     gvkey  adj_price  daily_return
 0   2001-06-04    1380.0  20.776815           NaN
 1   2001-06-05    1380.0  20.762423     -0.000693
 2   2001-06-06    1380.0  20.285316     -0.022979
 3   2001-06-07    1380.0  20.083923     -0.009928
 4   2001-06-08    1380.0  20.208591      0.006207
 ..         ...       ...        ...           ...
 242 2002-05-24  138743.0  11.919621      0.000000
 243 2002-05-28  138743.0  10.216818     -0.142857
 244 2002-05-29  138743.0   9.243786     -0.095238
 245 2002-05-30  138743.0   9.973558      0.078947
 246 2002-05-31  138743.0  11.189849      0.121952

 [31048 rows x 4 columns],
 '2002-09-03':       datadate     gvkey   adj_price  daily_return
 0   2001-09-04    1661.0  531.887451           NaN
 1   2001-09-05    1661.0  526.120056     -0.010843
 2   2001-09-06    1661.0  539.791138      0.025985
 3   2001-09-07    1661.0  525.479370     -0.026514
 4   2001-09-10    1661.0  528.683350      0.006097
 ..         ...       ...         ...           ...
 242 2002-08-26  110179.0    5.220900      0.011450
 243 2002-08-27  110179.0    5.169675     -0.009811
 244 2002-08-28  110179.0    5.161796     -0.001524
 245 2002-08-29  110179.0    5.201198      0.007633
 246 2002-08-30  110179.0    5.122392     -0.015152

 [30994 rows x 4 columns],
 '2002-12-02':       datadate     gvkey  adj_price  daily_return
 0   2001-12-03    7938.0   2.319574           NaN
 1   2001-12-04    7938.0   2.421266      0.043841
 2   2001-12-05    7938.0   2.458663      0.015445
 3   2001-12-06    7938.0   2.425888     -0.013330
 4   2001-12-07    7938.0   2.420004     -0.002425
 ..         ...       ...        ...           ...
 246 2002-11-22  138743.0   6.811212     -0.066666
 247 2002-11-25  138743.0   8.270755      0.214285
 248 2002-11-26  138743.0   8.757271      0.058824
 249 2002-11-27  138743.0   8.514013     -0.027778
 250 2002-11-29  138743.0   8.514013      0.000000

 [31437 rows x 4 columns],
 '2003-03-03':       datadate     gvkey  adj_price  daily_return
 0   2002-03-04    4430.0   6.625710           NaN
 1   2002-03-05    4430.0   6.681809      0.008467
 2   2002-03-06    4430.0   6.872146      0.028486
 3   2002-03-07    4430.0   6.922235      0.007289
 4   2002-03-08    4430.0   6.858123     -0.009262
 ..         ...       ...        ...           ...
 246 2003-02-24  110179.0   4.612560      0.013251
 247 2003-02-25  110179.0   4.701029      0.019180
 248 2003-02-26  110179.0   4.769395      0.014543
 249 2003-02-27  110179.0   4.857866      0.018550
 250 2003-02-28  110179.0   4.935183      0.015916

 [31285 rows x 4 columns],
 '2003-06-02':       datadate     gvkey  adj_price  daily_return
 0   2002-06-03    7938.0   2.900793           NaN
 1   2002-06-04    7938.0   2.845741     -0.018978
 2   2002-06-05    7938.0   2.816521     -0.010268
 3   2002-06-06    7938.0   2.754694     -0.021952
 4   2002-06-07    7938.0   2.758929      0.001537
 ..         ...       ...        ...           ...
 246 2003-05-23  110179.0   5.918108      0.015526
 247 2003-05-27  110179.0   5.971571      0.009034
 248 2003-05-28  110179.0   5.963343     -0.001378
 249 2003-05-29  110179.0   5.866136     -0.016301
 250 2003-05-30  110179.0   5.928985      0.010714

 [23499 rows x 4 columns],
 '2003-09-02':       datadate     gvkey  adj_price  daily_return
 0   2002-09-03    1380.0  17.433971           NaN
 1   2002-09-04    1380.0  17.473598      0.002273
 2   2002-09-05    1380.0  17.503305      0.001700
 3   2002-09-06    1380.0  17.706337      0.011600
 4   2002-09-09    1380.0  17.716255      0.000560
 ..         ...       ...        ...           ...
 246 2003-08-25  121382.0   2.979034     -0.012500
 247 2003-08-26  121382.0   3.007316      0.009494
 248 2003-08-27  121382.0   3.092161      0.028213
 249 2003-08-28  121382.0   3.111016      0.006097
 250 2003-08-29  121382.0   3.158153      0.015152

 [29718 rows x 4 columns],
 '2003-12-01':       datadate     gvkey  adj_price  daily_return
 0   2002-12-02    1380.0  13.847774           NaN
 1   2002-12-03    1380.0  14.148645      0.021727
 2   2002-12-04    1380.0  14.056641     -0.006503
 3   2002-12-05    1380.0  14.220753      0.011675
 4   2002-12-06    1380.0  14.312761      0.006470
 ..         ...       ...        ...           ...
 246 2003-11-21  110179.0   8.195517     -0.016352
 247 2003-11-24  110179.0   8.293437      0.011948
 248 2003-11-25  110179.0   8.365812      0.008727
 249 2003-11-26  110179.0   8.523333      0.018829
 250 2003-11-28  110179.0   8.523333      0.000000

 [33818 rows x 4 columns],
 '2004-03-01':       datadate     gvkey  adj_price  daily_return
 0   2003-03-03    4430.0   7.572071           NaN
 1   2003-03-04    4430.0   7.668050      0.012675
 2   2003-03-05    4430.0   7.649667     -0.002397
 3   2003-03-06    4430.0   7.672129      0.002936
 4   2003-03-07    4430.0   7.629247     -0.005589
 ..         ...       ...        ...           ...
 246 2004-02-23  113490.0   7.766702     -0.003339
 247 2004-02-24  113490.0   7.513019     -0.032663
 248 2004-02-25  113490.0   7.610591      0.012987
 249 2004-02-26  113490.0   7.708162      0.012820
 250 2004-02-27  113490.0   7.838256      0.016877

 [38396 rows x 4 columns],
 '2004-06-01':       datadate     gvkey  adj_price  daily_return
 0   2003-06-02    4430.0   8.421920           NaN
 1   2003-06-03    4430.0   8.473236      0.006093
 2   2003-06-04    4430.0   8.534812      0.007267
 3   2003-06-05    4430.0   8.315186     -0.025733
 4   2003-06-06    4430.0   8.298759     -0.001975
 ..         ...       ...        ...           ...
 247 2004-05-24  138743.0  22.995434      0.028562
 248 2004-05-25  138743.0  24.386574      0.060496
 249 2004-05-26  138743.0  24.394176      0.000312
 250 2004-05-27  138743.0  23.960875     -0.017763
 251 2004-05-28  138743.0  23.983675      0.000952

 [35359 rows x 4 columns],
 '2004-09-01':       datadate     gvkey  adj_price  daily_return
 0   2003-09-02    1380.0  12.143321           NaN
 1   2003-09-03    1380.0  12.234495      0.007508
 2   2003-09-04    1380.0  12.193974     -0.003312
 3   2003-09-05    1380.0  12.269948      0.006230
 4   2003-09-08    1380.0  12.459890      0.015480
 ..         ...       ...        ...           ...
 247 2004-08-25  260774.0   6.446667      0.002073
 248 2004-08-26  260774.0   6.480000      0.005171
 249 2004-08-27  260774.0   6.443333     -0.005658
 250 2004-08-30  260774.0   6.473333      0.004656
 251 2004-08-31  260774.0   6.496667      0.003605

 [36132 rows x 4 columns],
 '2004-12-01':       datadate     gvkey  adj_price  daily_return
 0   2003-12-01    7938.0   3.426866           NaN
 1   2003-12-02    7938.0   3.516356      0.026115
 2   2003-12-03    7938.0   3.565686      0.014029
 3   2003-12-04    7938.0   3.614579      0.013712
 4   2003-12-05    7938.0   3.611086     -0.000966
 ..         ...       ...        ...           ...
 247 2004-11-23  113490.0  10.784922      0.004849
 248 2004-11-24  113490.0  10.947540      0.015078
 249 2004-11-26  113490.0  10.993076      0.004159
 250 2004-11-29  113490.0  11.025598      0.002958
 251 2004-11-30  113490.0  10.980066     -0.004130

 [35880 rows x 4 columns],
 '2005-03-01':       datadate     gvkey  adj_price  daily_return
 0   2004-03-01    1380.0  16.972775           NaN
 1   2004-03-02    1380.0  16.639513     -0.019635
 2   2004-03-03    1380.0  16.772810      0.008011
 3   2004-03-04    1380.0  16.685665     -0.005196
 4   2004-03-05    1380.0  17.170155      0.029036
 ..         ...       ...        ...           ...
 247 2005-02-22  112111.0   3.879000      0.015445
 248 2005-02-23  112111.0   3.905000      0.006703
 249 2005-02-24  112111.0   3.801000     -0.026632
 250 2005-02-25  112111.0   3.750000     -0.013418
 251 2005-02-28  112111.0   3.683000     -0.017867

 [36021 rows x 4 columns],
 '2005-06-01':       datadate     gvkey  adj_price  daily_return
 0   2004-06-01    1380.0  18.766541           NaN
 1   2004-06-02    1380.0  18.653215     -0.006039
 2   2004-06-03    1380.0  18.367346     -0.015325
 3   2004-06-04    1380.0  18.053171     -0.017105
 4   2004-06-07    1380.0  18.573381      0.028815
 ..         ...       ...        ...           ...
 247 2005-05-24  121382.0  10.304062     -0.028444
 248 2005-05-25  121382.0  10.256926     -0.004575
 249 2005-05-26  121382.0  10.426616      0.016544
 250 2005-05-27  121382.0  10.577456      0.014467
 251 2005-05-31  121382.0  10.596308      0.001782

 [33330 rows x 4 columns],
 '2005-09-01':       datadate     gvkey  adj_price  daily_return
 0   2004-09-01    1380.0  21.057430           NaN
 1   2004-09-02    1380.0  21.331587      0.013019
 2   2004-09-03    1380.0  21.279848     -0.002425
 3   2004-09-07    1380.0  21.176403     -0.004861
 4   2004-09-08    1380.0  21.119503     -0.002687
 ..         ...       ...        ...           ...
 248 2005-08-25  160991.0   8.868759     -0.007268
 249 2005-08-26  160991.0   8.938332      0.007845
 250 2005-08-29  160991.0   8.873388     -0.007266
 251 2005-08-30  160991.0   8.924415      0.005750
 252 2005-08-31  160991.0   8.822369     -0.011434

 [39172 rows x 4 columns],
 '2005-12-01':       datadate     gvkey  adj_price  daily_return
 0   2004-12-01    2991.0  24.890772           NaN
 1   2004-12-02    2991.0  24.425337     -0.018699
 2   2004-12-03    2991.0  24.476532      0.002096
 3   2004-12-06    2991.0  24.578924      0.004183
 4   2004-12-07    2991.0  24.262430     -0.012877
 ..         ...       ...        ...           ...
 248 2005-11-23  160991.0  10.253091      0.012530
 249 2005-11-25  160991.0  10.271886      0.001833
 250 2005-11-28  160991.0  10.215499     -0.005489
 251 2005-11-29  160991.0  10.384659      0.016559
 252 2005-11-30  160991.0  10.563224      0.017195

 [37166 rows x 4 columns],
 '2006-03-01':       datadate     gvkey  adj_price  daily_return
 0   2005-03-01    1380.0  25.596958           NaN
 1   2005-03-02    1380.0  25.875744      0.010891
 2   2005-03-03    1380.0  26.613026      0.028493
 3   2005-03-04    1380.0  27.050714      0.016446
 4   2005-03-07    1380.0  26.925665     -0.004623
 ..         ...       ...        ...           ...
 247 2006-02-22  260774.0  23.049999      0.018259
 248 2006-02-23  260774.0  22.993334     -0.002458
 249 2006-02-24  260774.0  23.276667      0.012322
 250 2006-02-27  260774.0  23.706667      0.018473
 251 2006-02-28  260774.0  22.893333     -0.034308

 [36944 rows x 4 columns],
 '2006-06-01':       datadate     gvkey  adj_price  daily_return
 0   2005-06-01    4503.0  29.455168           NaN
 1   2005-06-02    4503.0  29.542782      0.002974
 2   2005-06-03    4503.0  29.455168     -0.002966
 3   2005-06-06    4503.0  29.687096      0.007874
 4   2005-06-07    4503.0  29.609789     -0.002604
 ..         ...       ...        ...           ...
 247 2006-05-24  121382.0  20.740110      0.041174
 248 2006-05-25  121382.0  22.135347      0.067272
 249 2006-05-26  121382.0  22.446453      0.014055
 250 2006-05-30  121382.0  21.626276     -0.036539
 251 2006-05-31  121382.0  21.579142     -0.002179

 [35072 rows x 4 columns],
 '2006-09-01':       datadate     gvkey  adj_price  daily_return
 0   2005-09-01    1380.0  35.190300           NaN
 1   2005-09-02    1380.0  34.744766     -0.012661
 2   2005-09-06    1380.0  34.883682      0.003998
 3   2005-09-07    1380.0  34.873188     -0.000301
 4   2005-09-08    1380.0  34.721169     -0.004359
 ..         ...       ...        ...           ...
 247 2006-08-25  260774.0  21.510000      0.021853
 248 2006-08-28  260774.0  22.070000      0.026034
 249 2006-08-29  260774.0  22.250000      0.008156
 250 2006-08-30  260774.0  22.620001      0.016629
 251 2006-08-31  260774.0  23.000000      0.016799

 [38456 rows x 4 columns],
 '2006-12-01':       datadate     gvkey  adj_price  daily_return
 0   2005-12-01    1380.0  33.186314           NaN
 1   2005-12-02    1380.0  32.965645     -0.006649
 2   2005-12-05    1380.0  33.078602      0.003427
 3   2005-12-06    1380.0  33.123276      0.001351
 4   2005-12-07    1380.0  32.548004     -0.017368
 ..         ...       ...        ...           ...
 247 2006-11-24  260774.0  32.610001     -0.006096
 248 2006-11-27  260774.0  31.920000     -0.021159
 249 2006-11-28  260774.0  32.209999      0.009085
 250 2006-11-29  260774.0  32.660000      0.013971
 251 2006-11-30  260774.0  32.930000      0.008267

 [36835 rows x 4 columns],
 '2007-03-01':       datadate     gvkey  adj_price  daily_return
 0   2006-03-01    1380.0  37.365822           NaN
 1   2006-03-02    1380.0  38.058311      0.018533
 2   2006-03-03    1380.0  37.879269     -0.004704
 3   2006-03-06    1380.0  36.623291     -0.033157
 4   2006-03-07    1380.0  36.336300     -0.007836
 ..         ...       ...        ...           ...
 246 2007-02-22  260774.0  36.310001     -0.020502
 247 2007-02-23  260774.0  36.169998     -0.003856
 248 2007-02-26  260774.0  35.310001     -0.023777
 249 2007-02-27  260774.0  33.470001     -0.052110
 250 2007-02-28  260774.0  33.310001     -0.004780

 [38520 rows x 4 columns],
 '2007-06-01':       datadate     gvkey  adj_price  daily_return
 0   2006-06-01    1380.0  39.534367           NaN
 1   2006-06-02    1380.0  40.183491      0.016419
 2   2006-06-05    1380.0  38.829792     -0.033688
 3   2006-06-06    1380.0  37.879829     -0.024465
 4   2006-06-07    1380.0  36.811123     -0.028213
 ..         ...       ...        ...           ...
 246 2007-05-24  260774.0  36.369999     -0.026759
 247 2007-05-25  260774.0  36.049999     -0.008798
 248 2007-05-29  260774.0  36.080002      0.000832
 249 2007-05-30  260774.0  37.349998      0.035199
 250 2007-05-31  260774.0  37.220001     -0.003481

 [32543 rows x 4 columns],
 '2007-09-04':       datadate     gvkey  adj_price  daily_return
 0   2006-09-05    1380.0  37.649853           NaN
 1   2006-09-06    1380.0  35.563038     -0.055427
 2   2006-09-07    1380.0  35.785206      0.006247
 3   2006-09-08    1380.0  34.737850     -0.029268
 4   2006-09-11    1380.0  33.396877     -0.038603
 ..         ...       ...        ...           ...
 245 2007-08-27  260774.0  30.090000     -0.021782
 246 2007-08-28  260774.0  28.719999     -0.045530
 247 2007-08-29  260774.0  28.910000      0.006616
 248 2007-08-30  260774.0  28.120001     -0.027326
 249 2007-08-31  260774.0  29.520000      0.049787

 [33158 rows x 4 columns],
 '2007-12-03':       datadate     gvkey  adj_price  daily_return
 0   2006-12-04    1380.0  40.254227           NaN
 1   2006-12-05    1380.0  39.824738     -0.010669
 2   2006-12-06    1380.0  40.906471      0.027162
 3   2006-12-07    1380.0  40.970085      0.001555
 4   2006-12-08    1380.0  41.288250      0.007766
 ..         ...       ...        ...           ...
 245 2007-11-26  260774.0  20.049999      0.012626
 246 2007-11-27  260774.0  21.120001      0.053367
 247 2007-11-28  260774.0  24.290001      0.150095
 248 2007-11-29  260774.0  23.260000     -0.042404
 249 2007-11-30  260774.0  23.750000      0.021066

 [38274 rows x 4 columns],
 '2008-03-03':       datadate     gvkey  adj_price  daily_return
 0   2007-03-05    1380.0  40.261032           NaN
 1   2007-03-06    1380.0  41.042038      0.019399
 2   2007-03-07    1380.0  41.583950      0.013204
 3   2007-03-08    1380.0  41.878803      0.007091
 4   2007-03-09    1380.0  42.078022      0.004757
 ..         ...       ...        ...           ...
 246 2008-02-25  260774.0  21.930000      0.043789
 247 2008-02-26  260774.0  21.760000     -0.007752
 248 2008-02-27  260774.0  21.959999      0.009191
 249 2008-02-28  260774.0  21.530001     -0.019581
 250 2008-02-29  260774.0  20.059999     -0.068277

 [37731 rows x 4 columns],
 '2008-06-02':       datadate     gvkey  adj_price  daily_return
 0   2007-06-04    1380.0  48.292816           NaN
 1   2007-06-05    1380.0  47.566212     -0.015046
 2   2007-06-06    1380.0  46.943378     -0.013094
 3   2007-06-07    1380.0  47.111050      0.003572
 4   2007-06-08    1380.0  47.166965      0.001187
 ..         ...       ...        ...           ...
 246 2008-05-23  260774.0  21.480000     -0.012414
 247 2008-05-27  260774.0  21.670000      0.008845
 248 2008-05-28  260774.0  22.430000      0.035072
 249 2008-05-29  260774.0  22.600000      0.007579
 250 2008-05-30  260774.0  22.459999     -0.006195

 [40749 rows x 4 columns],
 '2008-09-02':       datadate     gvkey  adj_price  daily_return
 0   2007-09-04    6788.0  35.033760           NaN
 1   2007-09-05    6788.0  36.078823      0.029830
 2   2007-09-06    6788.0  36.337799      0.007178
 3   2007-09-07    6788.0  35.607151     -0.020107
 4   2007-09-10    6788.0  35.283463     -0.009091

In [114]:
check=all_stocks_info['2018-03-01'].gvkey.unique()

In [115]:
for i in check:
    if i not in all_return_table['2018-03-01'].gvkey.unique():
        print(i)

In [116]:
df_price.head()

    gvkey    datadate  adj_price
0  126554  1999-11-18  26.511734
1  126554  1999-11-19  24.327538
2  126554  1999-11-22  26.511734
3  126554  1999-11-23  24.101578
4  126554  1999-11-24  24.741779

In [117]:
selected_stock[selected_stock.gvkey==34443]

      gvkey  predicted_return  trade_date
1706  34443          0.037525  2020-09-01
1746  34443          0.025963  2021-03-01
1778  34443          0.027404  2021-06-01
1810  34443          0.029716  2021-09-01
1895  34443          0.020289  2023-09-01
1928  34443          0.011908  2024-06-03
1949  34443          0.013305  2024-09-03

In [118]:
df_price[df_price.gvkey==34443]

         gvkey    datadate  adj_price
1113684  34443  2019-03-20  36.684479
1113685  34443  2019-03-21  36.080437
1113686  34443  2019-03-22  35.800518
1113687  34443  2019-03-25  36.205666
1113688  34443  2019-03-26  35.984673
...        ...         ...        ...
1115161  34443  2025-02-03  37.380001
1115162  34443  2025-02-04  38.549999
1115163  34443  2025-02-05  37.950001
1115164  34443  2025-02-06  38.770000
1115165  34443  2025-02-07  38.580002

[1482 rows x 3 columns]

## Save to pickle

In [119]:
with open('all_return_table.pickle', 'wb') as handle: 
    pickle.dump(all_return_table, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [120]:
with open('all_stocks_info.pickle', 'wb') as handle:
    pickle.dump(all_stocks_info, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [121]:
with open('all_return_table.pickle', 'rb') as handle:
    all_return_table = pickle.load(handle)

with open('all_stocks_info.pickle', 'rb') as handle:
    all_stocks_info = pickle.load(handle)

In [122]:
len(all_stocks_info)

96

In [ ]:
all_return_table['2009-09-01']

      datadate     gvkey  adj_price  daily_return
0   2008-09-02    5581.0  29.470863           NaN
1   2008-09-03    5581.0  29.193153     -0.009423
2   2008-09-04    5581.0  28.473398     -0.024655
3   2008-09-05    5581.0  27.957649     -0.018113
4   2008-09-08    5581.0  26.614464     -0.048044
..         ...       ...        ...           ...
247 2009-08-25  160479.0   6.021719      0.011988
248 2009-08-26  160479.0   5.980108     -0.006910
249 2009-08-27  160479.0   5.926609     -0.008946
250 2009-08-28  160479.0   6.057384      0.022066
251 2009-08-31  160479.0   5.884997     -0.028459

[35298 rows x 4 columns]

In [125]:
len(all_return_table)

96

In [ ]:
all_stocks_info['2018-03-01']

      gvkey  predicted_return  trade_date
0      5581          0.067435  2009-09-01
1      8151          0.051958  2009-09-01
2     11506          0.065671  2009-09-01
3     15247          0.058851  2009-09-01
4     20548          0.048703  2009-09-01
..      ...               ...         ...
136   30490          0.040536  2009-09-01
137   30822          0.040746  2009-09-01
138   65290          0.040426  2009-09-01
139  112111          0.041331  2009-09-01
140  160479          0.043454  2009-09-01

[141 rows x 3 columns]

# 4. Potfolio Optimization using pypfopt

In [127]:
# took under 5 minutes to run
from pypfopt import objective_functions
stocks_weight_table = pd.DataFrame([])

for i in range(len(trade_date)):
    # get selected stocks information
    p1_alldata=(all_stocks_info[trade_date[i]])
    # sort it by tic
    p1_alldata=p1_alldata.sort_values('gvkey')
    p1_alldata = p1_alldata.reset_index()
    del p1_alldata['index']
    
    print(p1_alldata)
    # get selected stocks tic
    p1_stock = p1_alldata.gvkey
    
    # get predicted return from selected stocks
    p1_predicted_return=p1_alldata.pivot_table(index = 'trade_date',columns = 'gvkey', values = 'predicted_return')
    # use the predicted returns as the Expected returns to feed into the portfolio object
    

    # get the 1-year historical return
    p1_return_table=all_return_table[trade_date[i]]
    p1_return_table_pivot=p1_return_table.pivot_table(index = 'datadate',columns = 'gvkey', values = 'daily_return')
    print(p1_return_table)
    selected_stocks = list(set(p1_predicted_return.columns).intersection(p1_return_table_pivot.columns))
    # use the 1-year historical return table to calculate covariance matrix between selected stocks
    p1_predicted_return = p1_predicted_return.loc[:, selected_stocks]
    p1_return_table_pivot = p1_return_table_pivot.loc[:, selected_stocks]
    S = risk_models.sample_cov(p1_return_table_pivot)
    mu = p1_predicted_return.T.values
   # del S.index.name 
    # mean variance
    ef_mean = EfficientFrontier(mu, S,weight_bounds=(0, 0.05))
    # raw_weights_mean = ef_mean.max_sharpe()
    raw_weights_mean = ef_mean.nonconvex_objective(
        objective_functions.sharpe_ratio,
        objective_args = (ef_mean.expected_returns, ef_mean.cov_matrix),
        weights_sum_to_one = True
    )
    cleaned_weights_mean = ef_mean.clean_weights()
    # print(f'output{cleaned_weights_mean}')
    #print(raw_weights_mean)
    #ef.portfolio_performance(verbose=True)
    #print("cleaned_weights_mean: ", cleaned_weights_mean)

    # minimum variance
    ef_min = EfficientFrontier([0]*len(mu), S,weight_bounds=(0, 0.05))
   # raw_weights_min = ef_min.max_sharpe()
    raw_weights_min = ef_min.nonconvex_objective(
        objective_functions.sharpe_ratio,
        objective_args = (ef_min.expected_returns, ef_min.cov_matrix),
        weights_sum_to_one = True
    )
    cleaned_weights_min = ef_min.clean_weights()
    #print(cleaned_weights_min)
    print("cleaned_weights_min: ", cleaned_weights_min)

    idx = np.isin(p1_alldata.gvkey, selected_stocks)
    p1_alldata["mean_weight"] = 0
    p1_alldata.loc[idx, 'mean_weight'] = list(cleaned_weights_mean.values())

    p1_alldata["min_weight"] = 0
    p1_alldata.loc[idx, 'min_weight'] = list(cleaned_weights_min.values())

    p1_alldata["equal_weight"] = 0
    p1_alldata.loc[idx, 'equal_weight'] = np.ones(len(cleaned_weights_mean)) / len(cleaned_weights_mean)
    # p1_alldata["mean_weight"] = 0
    # p1_alldata['mean_weight'][idx] = list(cleaned_weights_mean.values())
    # p1_alldata["min_weight"] = 0
    # p1_alldata['min_weight'][idx] = list(cleaned_weights_min.values())
    # p1_alldata["equal_weight"] = 0
    # p1_alldata['equal_weight'][idx] = np.ones(len(cleaned_weights_mean.values())) / len(cleaned_weights_mean.values())
    #ef.portfolio_performance(verbose=True)
    
    stocks_weight_table = pd.concat([stocks_weight_table, p1_alldata])
    print(trade_date[i], ": Done")

      gvkey  predicted_return  trade_date
0      1078          0.034301  2001-03-01
1      1661          0.019528  2001-03-01
2      2086          0.037875  2001-03-01
3      2220          0.033051  2001-03-01
4      2255          0.021322  2001-03-01
..      ...               ...         ...
104  136725          0.052153  2001-03-01
105  139665          0.039613  2001-03-01
106  140541          0.021322  2001-03-01
107  141459          0.025537  2001-03-01
108  141913          0.038280  2001-03-01

[109 rows x 3 columns]
      datadate     gvkey   adj_price  daily_return
0   2000-03-01    1661.0  806.375793           NaN
1   2000-03-02    1661.0  837.082153      0.038079
2   2000-03-03    1661.0  799.700623     -0.044657
3   2000-03-06    1661.0  819.726257      0.025041
4   2000-03-07    1661.0  854.437744      0.042345
..         ...       ...         ...           ...
247 2001-02-22  125595.0   17.000000     -0.052265
248 2001-02-23  125595.0   19.187500      0.128676
249 2001-02-26  125595.0   20.062500      0.045603
250 2001-02-27  125595.0   17.812500     -0.112150
251 2001-02-28  125595.0   16.937500     -0.049123

[26724 rows x 4 columns]
cleaned_weights_min:  OrderedDict([(5125.0, 0.00917), (4108.0, 0.00917), (2574.0, 0.00917), (66065.0, 0.00917), (28180.0, 0.00917), (136725.0, 0.00917), (13341.0, 0.00917), (28191.0, 0.00917), (11811.0, 0.00917), (2086.0, 0.00917), (29736.0, 0.00917), (10793.0, 0.00917), (24617.0, 0.00917), (61483.0, 0.00917), (112168.0, 0.00917), (5680.0, 0.00917), (30259.0, 0.00917), (13365.0, 0.00917), (1078.0, 0.00917), (9783.0, 0.00917), (15417.0, 0.00917), (29241.0, 0.00917), (8253.0, 0.00917), (4674.0, 0.00917), (28742.0, 0.00917), (6216.0, 0.00917), (5709.0, 0.00917), (6733.0, 0.00917), (14418.0, 0.00917), (9299.0, 0.00917), (12884.0, 0.00917), (141913.0, 0.00917), (63080.0, 0.00917), (4601.0, 0.00917), (6268.0, 0.00917), (1661.0, 0.00917), (133768.0, 0.00917), (141459.0, 0.00917), (3735.0, 0.00917), (5783.0, 0.00917), (61591.0, 0.00917), (63643.0, 0.00917), (125595.0, 0.00917), (15520.0, 0.00917), (8358.0, 0.00917), (2220.0, 0.00917), (6829.0, 0.00917), (7343.0, 0.00917), (10420.0, 0.00917), (13498.0, 0.00917), (28349.0, 0.00917), (7875.0, 0.00917), (63172.0, 0.00917), (24782.0, 0.00917), (2255.0, 0.00917), (24800.0, 0.00917), (7906.0, 0.00917), (7922.0, 0.00917), (11506.0, 0.00917), (133366.0, 0.00917), (140541.0, 0.00917), (23809.0, 0.00917), (10499.0, 0.00917), (23812.0, 0.00917), (3336.0, 0.00917), (8463.0, 0.00917), (24344.0, 0.00917), (24856.0, 0.00917), (120093.0, 0.00917), (3362.0, 0.00917), (61739.0, 0.00917), (11060.0, 0.00917), (24379.0, 0.00917), (27965.0, 0.00917), (66368.0, 0.00917), (6994.0, 0.00917), (8530.0, 0.00917), (25434.0, 0.00917), (114524.0, 0.00917), (29028.0, 0.00917), (64356.0, 0.00917), (6502.0, 0.00917), (62823.0, 0.00917), (15208.0, 0.00917), (11636.0, 0.00917), (121718.0, 0.00917), (14225.0, 0.00917), (139665.0, 0.00917), (63892.0, 0.00917), (15267.0, 0.00917), (3497.0, 0.00917), (2991.0, 0.00917), (30137.0, 0.00917), (7620.0, 0.00917), (114628.0, 0.00917), (61388.0, 0.00917), (5581.0, 0.00917), (12756.0, 0.00917), (28118.0, 0.00917), (29150.0, 0.00917), (7647.0, 0.00917), (66016.0, 0.00917), (14822.0, 0.00917), (61420.0, 0.00917), (7154.0, 0.00917), (2547.0, 0.00917), (3062.0, 0.00917), (6649.0, 0.00917), (11259.0, 0.00917)])
2001-03-01 : Done
      gvkey  predicted_return  trade_date
0      1078          0.030737  2001-06-01
1      1230          0.028313  2001-06-01
2      1380          0.031428  2001-06-01
3      1661          0.031428  2001-06-01
4      1678          0.031428  2001-06-01
..      ...               ...         ...
138  133366          0.046809  2001-06-01
139  138743          0.058683  2001-06-01
140  140541          0.090700  2001-06-01
141  141459          0.027498  2001-06-01
142  141913          0.049402  2001-06-01

[143 rows x 3 columns]
      datadate     gvkey  adj_price  daily_return
0   2000-06-01    1380.0  15.726690           NaN
1   2000-06-02    1380.0  14.896629     -0.052780
2   2000-06-05    1380.0  15.000383      0.006965
3   2000-06-06    1380.0  15.593284      0.039526
4   2000-06-07    1380.0  15.252367     -0.021863
..         ...       ...        ...           ...
247 2001-05-24  138743.0  37.461662      0.076923
248 2001-05-25  138743.0  36.488640     -0.025974
249 2001-05-29  138743.0  35.515602     -0.026667
250 2001-05-30  138743.0  31.623470     -0.109589
251 2001-05-31  138743.0  31.623470      0.000000

[35607 rows x 4 columns]
cleaned_weights_min:  OrderedDict([(62984.0, 0.00699), (64030.0, 0.00699), (3619.0, 0.00699), (11300.0, 0.00699), (121382.0, 0.00699), (29736.0, 0.00699), (10793.0, 0.00699), (30259.0, 0.00699), (13365.0, 0.00699), (1078.0, 0.00699), (9783.0, 0.00699), (29751.0, 0.00699), (15417.0, 0.00699), (8762.0, 0.00699), (29241.0, 0.00699), (61494.0, 0.00699), (3650.0, 0.00699), (4674.0, 0.00699), (20548.0, 0.00699), (6216.0, 0.00699), (7241.0, 0.00699), (12884.0, 0.00699), (14934.0, 0.00699), (141913.0, 0.00699), (4699.0, 0.00699), (16478.0, 0.00699), (110179.0, 0.00699), (31846.0, 0.00699), (4199.0, 0.00699), (11376.0, 0.00699), (64630.0, 0.00699), (9850.0, 0.00699), (6268.0, 0.00699), (6781.0, 0.00699), (1661.0, 0.00699), (6788.0, 0.00699), (24197.0, 0.00699), (2184.0, 0.00699), (1678.0, 0.00699), (10894.0, 0.00699), (141459.0, 0.00699), (3735.0, 0.00699), (10903.0, 0.00699), (61591.0, 0.00699), (3226.0, 0.00699), (1690.0, 0.00699), (5786.0, 0.00699), (125595.0, 0.00699), (3231.0, 0.00699), (10405.0, 0.00699), (8358.0, 0.00699), (2220.0, 0.00699), (28338.0, 0.00699), (1722.0, 0.00699), (2751.0, 0.00699), (6338.0, 0.00699), (8898.0, 0.00699), (7366.0, 0.00699), (7881.0, 0.00699), (29901.0, 0.00699), (1230.0, 0.00699), (17110.0, 0.00699), (2269.0, 0.00699), (24800.0, 0.00699), (7906.0, 0.00699), (7922.0, 0.00699), (11506.0, 0.00699), (121077.0, 0.00699), (133366.0, 0.00699), (9465.0, 0.00699), (12540.0, 0.00699), (24316.0, 0.00699), (140541.0, 0.00699), (64768.0, 0.00699), (7938.0, 0.00699), (2312.0, 0.00699), (10504.0, 0.00699), (8463.0, 0.00699), (25880.0, 0.00699), (30490.0, 0.00699), (120093.0, 0.00699), (11550.0, 0.00699), (14624.0, 0.00699), (3362.0, 0.00699), (7970.0, 0.00699), (11554.0, 0.00699), (61739.0, 0.00699), (7985.0, 0.00699), (24379.0, 0.00699), (5439.0, 0.00699), (8007.0, 0.00699), (4430.0, 0.00699), (113490.0, 0.00699), (9555.0, 0.00699), (24405.0, 0.00699), (25434.0, 0.00699), (12124.0, 0.00699), (1891.0, 0.00699), (1380.0, 0.00699), (8549.0, 0.00699), (6502.0, 0.00699), (9063.0, 0.00699), (62823.0, 0.00699), (11636.0, 0.00699), (10614.0, 0.00699), (121718.0, 0.00699), (2436.0, 0.00699), (8068.0, 0.00699), (61325.0, 0.00699), (4494.0, 0.00699), (15247.0, 0.00699), (14225.0, 0.00699), (63892.0, 0.00699), (105365.0, 0.00699), (4503.0, 0.00699), (11672.0, 0.00699), (8099.0, 0.00699), (4517.0, 0.00699), (6565.0, 0.00699), (20904.0, 0.00699), (3497.0, 0.00699), (2991.0, 0.00699), (3504.0, 0.00699), (5046.0, 0.00699), (12726.0, 0.00699), (30137.0, 0.00699), (7620.0, 0.00699), (114628.0, 0.00699), (14282.0, 0.00699), (61388.0, 0.00699), (5581.0, 0.00699), (26061.0, 0.00699), (8151.0, 0.00699), (7647.0, 0.00699), (66016.0, 0.00699), (28139.0, 0.00699), (112111.0, 0.00699), (9203.0, 0.00699), (29173.0, 0.00699), (3062.0, 0.00699), (138743.0, 0.00699), (6136.0, 0.00699), (11259.0, 0.00699)])
2001-06-01 : Done
      gvkey  predicted_return  trade_date
0      1279          0.032737  2001-09-04
1      1327          0.104303  2001-09-04
2      1380          0.032324  2001-09-04
3      1440          0.032737  2001-09-04
4      1449          0.048198  2001-09-04
..      ...               ...         ...
143  139665          0.053850  2001-09-04
144  140541          0.060220  2001-09-04
145  141384          0.055427  2001-09-04
146  141459          0.076370  2001-09-04
147  143912          0.031746  2001-09-04

[148 rows x 3 columns]
      datadate     gvkey  adj_price  daily_return
0   2000-09-05    1380.0  16.623709           NaN
1   2000-09-06    1380.0  16.846550      0.013405
2   2000-09-07    1380.0  16.965395      0.007055
3   2000-09-08    1380.0  16.638575     -0.019264
4   2000-09-11    1380.0  16.712845      0.004464
..         ...       ...        ...           ...
246 2001-08-27  138743.0  21.649923     -0.053191
247 2001-08-28  138743.0  20.920147     -0.033708
248 2001-08-29  138743.0  18.974083     -0.093023
249 2001-08-30  138743.0  17.757801     -0.064102
250 2001-08-31  138743.0  17.757801      0.000000

[36554 rows x 4 columns]
cleaned_weights_min:  OrderedDict([(10247.0, 0.00676), (62984.0, 0.00676), (117768.0, 0.00676), (6669.0, 0.00676), (136725.0, 0.00676), (13341.0, 0.00676), (64030.0, 0.00676), (11811.0, 0.00676), (28195.0, 0.00676), (29733.0, 0.00676), (121382.0, 0.00676), (143912.0, 0.00676), (10793.0, 0.00676), (61483.0, 0.00676), (30259.0, 0.00676), (13365.0, 0.00676), (15414.0, 0.00676), (29751.0, 0.00676), (15417.0, 0.00676), (29241.0, 0.00676), (8253.0, 0.00676), (1598.0, 0.00676), (4674.0, 0.00676), (20548.0, 0.00676), (3144.0, 0.00676), (6216.0, 0.00676), (141384.0, 0.00676), (6733.0, 0.00676), (14934.0, 0.00676), (2136.0, 0.00676), (7257.0, 0.00676), (16478.0, 0.00676), (4199.0, 0.00676), (8810.0, 0.00676), (4213.0, 0.00676), (9846.0, 0.00676), (8823.0, 0.00676), (9850.0, 0.00676), (1661.0, 0.00676), (61567.0, 0.00676), (6788.0, 0.00676), (1678.0, 0.00676), (31887.0, 0.00676), (141459.0, 0.00676), (10903.0, 0.00676), (24216.0, 0.00676), (1690.0, 0.00676), (63643.0, 0.00676), (125595.0, 0.00676), (15520.0, 0.00676), (13988.0, 0.00676), (6821.0, 0.00676), (10920.0, 0.00676), (9899.0, 0.00676), (6829.0, 0.00676), (7343.0, 0.00676), (28338.0, 0.00676), (13498.0, 0.00676), (8898.0, 0.00676), (63172.0, 0.00676), (7366.0, 0.00676), (30923.0, 0.00676), (29901.0, 0.00676), (7892.0, 0.00676), (17110.0, 0.00676), (24800.0, 0.00676), (5860.0, 0.00676), (11506.0, 0.00676), (121077.0, 0.00676), (133366.0, 0.00676), (9465.0, 0.00676), (140541.0, 0.00676), (1279.0, 0.00676), (7938.0, 0.00676), (10499.0, 0.00676), (2312.0, 0.00676), (10504.0, 0.00676), (65290.0, 0.00676), (24856.0, 0.00676), (27928.0, 0.00676), (120093.0, 0.00676), (3362.0, 0.00676), (7974.0, 0.00676), (7977.0, 0.00676), (1327.0, 0.00676), (7991.0, 0.00676), (3897.0, 0.00676), (5439.0, 0.00676), (11584.0, 0.00676), (4430.0, 0.00676), (16721.0, 0.00676), (6994.0, 0.00676), (9555.0, 0.00676), (113490.0, 0.00676), (12124.0, 0.00676), (114524.0, 0.00676), (1891.0, 0.00676), (1380.0, 0.00676), (8549.0, 0.00676), (29028.0, 0.00676), (31587.0, 0.00676), (62823.0, 0.00676), (4973.0, 0.00676), (5492.0, 0.00676), (61302.0, 0.00676), (10115.0, 0.00676), (2436.0, 0.00676), (8068.0, 0.00676), (4494.0, 0.00676), (15247.0, 0.00676), (12689.0, 0.00676), (14225.0, 0.00676), (139665.0, 0.00676), (63892.0, 0.00676), (105365.0, 0.00676), (4503.0, 0.00676), (7065.0, 0.00676), (64925.0, 0.00676), (1440.0, 0.00676), (6565.0, 0.00676), (62374.0, 0.00676), (20904.0, 0.00676), (1449.0, 0.00676), (3497.0, 0.00676), (2991.0, 0.00676), (3504.0, 0.00676), (30137.0, 0.00676), (7620.0, 0.00676), (114628.0, 0.00676), (5581.0, 0.00676), (11220.0, 0.00676), (8151.0, 0.00676), (4058.0, 0.00676), (138205.0, 0.00676), (7647.0, 0.00676), (5606.0, 0.00676), (30697.0, 0.00676), (61420.0, 0.00676), (112111.0, 0.00676), (7154.0, 0.00676), (8692.0, 0.00676), (29173.0, 0.00676), (3062.0, 0.00676), (138743.0, 0.00676), (6136.0, 0.00676), (4601.0, 0.00676), (11259.0, 0.00676), (4605.0, 0.00676)])
2001-09-04 : Done
      gvkey  predicted_return  trade_date
0      1075          0.042474  2001-12-03
1      1209          0.022708  2001-12-03
2      1230          0.033712  2001-12-03
3      1327          0.103086  2001-12-03
4      1380          0.028207  2001-12-03
..      ...               ...         ...
138  133768          0.053879  2001-12-03
139  138205          0.051856  2001-12-03
140  139665          0.062495  2001-12-03
141  143912          0.041234  2001-12-03
142  145046          0.048425  2001-12-03

[143 rows x 3 columns]
      datadate     gvkey  adj_price  daily_return
0   2000-12-04    1380.0  14.828528           NaN
1   2000-12-05    1380.0  14.352110     -0.032129
2   2000-12-06    1380.0  14.352110      0.000000
3   2000-12-07    1380.0  14.143685     -0.014522
4   2000-12-08    1380.0  14.292555      0.010526
..         ...       ...        ...           ...
242 2001-11-26  112111.0   1.864000      0.022490
243 2001-11-27  112111.0   1.815000     -0.026288
244 2001-11-28  112111.0   1.810000     -0.002755
245 2001-11-29  112111.0   1.949000      0.076796
246 2001-11-30  112111.0   1.937000     -0.006157

[34829 rows x 4 columns]
cleaned_weights_min:  OrderedDict([(11264.0, 0.00699), (7171.0, 0.00699), (6669.0, 0.00699), (2574.0, 0.00699), (13341.0, 0.00699), (9248.0, 0.00699), (25124.0, 0.00699), (2086.0, 0.00699), (29736.0, 0.00699), (24617.0, 0.00699), (143912.0, 0.00699), (61483.0, 0.00699), (1075.0, 0.00699), (30259.0, 0.00699), (8247.0, 0.00699), (15417.0, 0.00699), (8253.0, 0.00699), (1598.0, 0.00699), (4674.0, 0.00699), (20548.0, 0.00699), (28742.0, 0.00699), (6216.0, 0.00699), (65609.0, 0.00699), (5709.0, 0.00699), (6733.0, 0.00699), (8272.0, 0.00699), (12884.0, 0.00699), (30293.0, 0.00699), (14934.0, 0.00699), (16478.0, 0.00699), (2146.0, 0.00699), (65640.0, 0.00699), (5742.0, 0.00699), (4213.0, 0.00699), (9846.0, 0.00699), (8823.0, 0.00699), (64630.0, 0.00699), (1661.0, 0.00699), (6788.0, 0.00699), (133768.0, 0.00699), (1678.0, 0.00699), (31887.0, 0.00699), (145046.0, 0.00699), (5783.0, 0.00699), (24216.0, 0.00699), (61591.0, 0.00699), (1690.0, 0.00699), (3226.0, 0.00699), (125595.0, 0.00699), (15520.0, 0.00699), (1704.0, 0.00699), (12459.0, 0.00699), (2220.0, 0.00699), (28338.0, 0.00699), (10420.0, 0.00699), (1209.0, 0.00699), (8898.0, 0.00699), (7366.0, 0.00699), (30923.0, 0.00699), (1230.0, 0.00699), (24800.0, 0.00699), (5860.0, 0.00699), (3813.0, 0.00699), (10983.0, 0.00699), (11506.0, 0.00699), (121077.0, 0.00699), (133366.0, 0.00699), (111864.0, 0.00699), (9465.0, 0.00699), (25340.0, 0.00699), (1794.0, 0.00699), (7938.0, 0.00699), (10499.0, 0.00699), (23812.0, 0.00699), (2312.0, 0.00699), (10504.0, 0.00699), (8463.0, 0.00699), (4885.0, 0.00699), (24344.0, 0.00699), (24856.0, 0.00699), (27928.0, 0.00699), (120093.0, 0.00699), (3362.0, 0.00699), (7970.0, 0.00699), (7974.0, 0.00699), (1327.0, 0.00699), (64821.0, 0.00699), (5439.0, 0.00699), (11584.0, 0.00699), (8007.0, 0.00699), (4430.0, 0.00699), (6994.0, 0.00699), (24405.0, 0.00699), (2403.0, 0.00699), (1380.0, 0.00699), (8549.0, 0.00699), (6502.0, 0.00699), (62823.0, 0.00699), (15208.0, 0.00699), (4973.0, 0.00699), (12141.0, 0.00699), (10614.0, 0.00699), (61302.0, 0.00699), (121718.0, 0.00699), (1913.0, 0.00699), (2436.0, 0.00699), (8068.0, 0.00699), (65417.0, 0.00699), (4494.0, 0.00699), (15247.0, 0.00699), (12689.0, 0.00699), (14225.0, 0.00699), (139665.0, 0.00699), (63892.0, 0.00699), (4503.0, 0.00699), (7063.0, 0.00699), (11672.0, 0.00699), (64925.0, 0.00699), (20904.0, 0.00699), (1449.0, 0.00699), (3497.0, 0.00699), (2991.0, 0.00699), (12726.0, 0.00699), (9667.0, 0.00699), (7620.0, 0.00699), (114628.0, 0.00699), (29127.0, 0.00699), (5581.0, 0.00699), (3026.0, 0.00699), (11220.0, 0.00699), (7637.0, 0.00699), (28629.0, 0.00699), (8151.0, 0.00699), (138205.0, 0.00699), (29150.0, 0.00699), (66016.0, 0.00699), (61420.0, 0.00699), (112111.0, 0.00699), (29173.0, 0.00699), (3062.0, 0.00699), (6136.0, 0.00699), (4601.0, 0.00699), (11259.0, 0.00699)])
2001-12-03 : Done
      gvkey  predicted_return  trade_date
0      1075          0.036927  2002-03-01
1      1078          0.071673  2002-03-01
2      1230          0.039464  2002-03-01
3      1380          0.033133  2002-03-01
4      1449          0.061158  2002-03-01
..      ...               ...         ...
126  140541          0.055720  2002-03-01
127  143912          0.040366  2002-03-01
128  145049          0.052823  2002-03-01
129  145552          0.084797  2002-03-01
130  145701          0.054754  2002-03-01

[131 rows x 3 columns]
      datadate     gvkey  adj_price  daily_return
0   2001-03-01    1380.0  17.291304           NaN
1   2001-03-02    1380.0  17.673374      0.022096
2   2001-03-05    1380.0  18.026802      0.019998
3   2001-03-06    1380.0  18.306181      0.015498
4   2001-03-07    1380.0  18.540205      0.012784
..         ...       ...        ...           ...
243 2002-02-22  113490.0   3.629665     -0.021052
244 2002-02-25  113490.0   3.811799      0.050179
245 2002-02-26  113490.0   3.889858      0.020478
246 2002-02-27  113490.0   4.098010      0.053511
247 2002-02-28  113490.0   4.039466     -0.014286

[31577 rows x 4 columns]
cleaned_weights_min:  OrderedDict([(62984.0, 0.00763), (6669.0, 0.00763), (2574.0, 0.00763), (13341.0, 0.00763), (9248.0, 0.00763), (29733.0, 0.00763), (29736.0, 0.00763), (24617.0, 0.00763), (143912.0, 0.00763), (61483.0, 0.00763), (4145.0, 0.00763), (1075.0, 0.00763), (30259.0, 0.00763), (13365.0, 0.00763), (1078.0, 0.00763), (60979.0, 0.00763), (15417.0, 0.00763), (8253.0, 0.00763), (1598.0, 0.00763), (4674.0, 0.00763), (20548.0, 0.00763), (65609.0, 0.00763), (5709.0, 0.00763), (6733.0, 0.00763), (8272.0, 0.00763), (11856.0, 0.00763), (30293.0, 0.00763), (14934.0, 0.00763), (16478.0, 0.00763), (31846.0, 0.00763), (4199.0, 0.00763), (65640.0, 0.00763), (8810.0, 0.00763), (5229.0, 0.00763), (64630.0, 0.00763), (8823.0, 0.00763), (1661.0, 0.00763), (4737.0, 0.00763), (6788.0, 0.00763), (2184.0, 0.00763), (133768.0, 0.00763), (1678.0, 0.00763), (145552.0, 0.00763), (5783.0, 0.00763), (10903.0, 0.00763), (145049.0, 0.00763), (3226.0, 0.00763), (5786.0, 0.00763), (4764.0, 0.00763), (24731.0, 0.00763), (12459.0, 0.00763), (28338.0, 0.00763), (29875.0, 0.00763), (25279.0, 0.00763), (6338.0, 0.00763), (7366.0, 0.00763), (30923.0, 0.00763), (29901.0, 0.00763), (1230.0, 0.00763), (7906.0, 0.00763), (5860.0, 0.00763), (4839.0, 0.00763), (11506.0, 0.00763), (133366.0, 0.00763), (9465.0, 0.00763), (25340.0, 0.00763), (140541.0, 0.00763), (1794.0, 0.00763), (7938.0, 0.00763), (2312.0, 0.00763), (10504.0, 0.00763), (27914.0, 0.00763), (25880.0, 0.00763), (120093.0, 0.00763), (29984.0, 0.00763), (3362.0, 0.00763), (11554.0, 0.00763), (145701.0, 0.00763), (64821.0, 0.00763), (5439.0, 0.00763), (13125.0, 0.00763), (8007.0, 0.00763), (4430.0, 0.00763), (6994.0, 0.00763), (8530.0, 0.00763), (9555.0, 0.00763), (113490.0, 0.00763), (2403.0, 0.00763), (1380.0, 0.00763), (8549.0, 0.00763), (6502.0, 0.00763), (29028.0, 0.00763), (62823.0, 0.00763), (4973.0, 0.00763), (3439.0, 0.00763), (1913.0, 0.00763), (4988.0, 0.00763), (8068.0, 0.00763), (13700.0, 0.00763), (65417.0, 0.00763), (61325.0, 0.00763), (4494.0, 0.00763), (15247.0, 0.00763), (12689.0, 0.00763), (14225.0, 0.00763), (139665.0, 0.00763), (63892.0, 0.00763), (4503.0, 0.00763), (2968.0, 0.00763), (11672.0, 0.00763), (5543.0, 0.00763), (1449.0, 0.00763), (2991.0, 0.00763), (3505.0, 0.00763), (12726.0, 0.00763), (30137.0, 0.00763), (9667.0, 0.00763), (7620.0, 0.00763), (5581.0, 0.00763), (26061.0, 0.00763), (5071.0, 0.00763), (12756.0, 0.00763), (7637.0, 0.00763), (8151.0, 0.00763), (11228.0, 0.00763), (7647.0, 0.00763), (112111.0, 0.00763), (29173.0, 0.00763), (3062.0, 0.00763), (11259.0, 0.00763), (4093.0, 0.00763)])
2002-03-01 : Done
      gvkey  predicted_return  trade_date
0      1230          0.046133  2002-06-03
1      1380          0.035979  2002-06-03
2      1661          0.035979  2002-06-03
3      1678          0.035979  2002-06-03
4      1891          0.029863  2002-06-03
..      ...               ...         ...
124  143912          0.038309  2002-06-03
125  145552          0.070369  2002-06-03
126  146017          0.022603  2002-06-03
127  147398          0.035979  2002-06-03
128  147579          0.103582  2002-06-03

[129 rows x 3 columns]
      datadate     gvkey  adj_price  daily_return
0   2001-06-04    1380.0  20.776815           NaN
1   2001-06-05    1380.0  20.762423     -0.000693

In [128]:
stocks_weight_table.shape

(17551, 6)

In [129]:
stocks_weight_table.head()

   gvkey  predicted_return  trade_date  mean_weight  min_weight  equal_weight
0   1078          0.034301  2001-03-01      0.00917     0.00917      0.009174
1   1661          0.019528  2001-03-01      0.00917     0.00917      0.009174
2   2086          0.037875  2001-03-01      0.00917     0.00917      0.009174
3   2220          0.033051  2001-03-01      0.00917     0.00917      0.009174
4   2255          0.021322  2001-03-01      0.00917     0.00917      0.009174

## save to excel or csv

In [130]:
df_mean = pd.DataFrame()
df_mean['trade_date'] = stocks_weight_table['trade_date']
df_mean['gvkey'] = stocks_weight_table['gvkey']
df_mean['weights'] = stocks_weight_table['mean_weight']
df_mean['predicted_return'] = stocks_weight_table['predicted_return']
df_mean.to_excel("mean_weighted.xlsx")

In [131]:
df_min = pd.DataFrame()
df_min['trade_date'] = stocks_weight_table['trade_date']
df_min['gvkey'] = stocks_weight_table['gvkey']
df_min['weights'] = stocks_weight_table['min_weight']
df_min['predicted_return'] = stocks_weight_table['predicted_return']
df_min.to_excel("minimum_weighted.xlsx")

In [132]:
df_equal = pd.DataFrame()
df_equal['trade_date'] = stocks_weight_table['trade_date']
df_equal['gvkey'] = stocks_weight_table['gvkey']
df_equal['weights'] = stocks_weight_table['equal_weight']
df_equal['predicted_return'] = stocks_weight_table['predicted_return']
df_equal.to_excel("equally_weighted.xlsx")